"""Initial migration4

Revision ID: 543478123191
Revises: b88ac2faa08d
Create Date: 2026-02-25 11:07:51.730182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543478123191'
down_revision: Union[str, Sequence[str], None] = 'b88ac2faa08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Comment_comment1'), table_name='Comment')
    op.drop_column('Comment', 'comment1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('comment1', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_Comment_comment1'), 'Comment', ['comment1'], unique=False)
    # ### end Alembic commands ###
