"""Initial migration6

Revision ID: d6b0a9543d71
Revises: 370d2f41e2a2
Create Date: 2026-02-25 11:11:16.243393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b0a9543d71'
down_revision: Union[str, Sequence[str], None] = '370d2f41e2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Comment_xxx'), table_name='Comment')
    op.drop_column('Comment', 'xxx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('xxx', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_Comment_xxx'), 'Comment', ['xxx'], unique=False)
    # ### end Alembic commands ###
